server/config/routes.rb
Server::Application.routes.draw do

  match 'login' => 'access#login', :as => :login
  match 'logout' => 'access#logout', :as => :logout
  match 'callback' => 'access#callback', :as => :callback

  match 'info' => 'info#index', :as => :info, :via => :get
  match 'info/:id' => 'info#update', :via => :put

  match 'skill_tree/learn' => 'skill_tree#learn', :via => :put
  match 'skill_tree/query/:uid/:sid' => 'skill_tree#query', :via => :get

  match 'store' => 'store#update', :via => :put
  match 'store' => 'store#index', :via => :get
  match 'store/:id' => 'store#show', :via => :get
  match 'store/:id/sell' => 'store#sell', :via => :put
  match 'store/:id/buy' => 'store#buy', :via => :put

  match 'monster' => 'monster#index', :via => :get
  match 'monster' => 'monster#create', :via => :put
  match 'monster/:id/hit' => 'monster#hit', :via => :put

  match 'map' => 'main#map', :as => :map
  match 'item' => 'item#index', :as => :item

  match 'attack/:id' => 'battle#attack', :via => :put

  match 'chat' => 'chat#new', :via => :put

  root :to => 'main#index'

end

server/app/controllers/main_controller.rb
class MainController < ApplicationController
  before_filter :ensure_login, :only => :map

  def index
  end

  def map
    @user = current_user
    render :layout => nil
  end
end

server/app/helpers/main_helper.rb
module MainHelper
end

server/app/views/main/index.erb
<html>
<head>
   <title>Abelian Kindom</title>
</head>
<body>
   <h1>Login with Facebook</h1>
   <p><%= link_to "Login", login_path %></p>
</body>
</html>

server/app/views/main/map.erb
<!DOCTYPE html>
<html>
   <head>
      <title>Abelian Kingdom</title>
      <script>
      window.userID = <%= @user.id %>;
      </script>
      <meta name="viewport" content="initial-scale=1.0, user-scalable=no" />
      <link href='http://fonts.googleapis.com/css?family=Armata' rel='stylesheet' type='text/css'>
      <%= stylesheet_link_tag 'application' %>
      <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?key=AIzaSyBoylQYyk6ciYJtMWWRDXnxHkAk7mB8vOw&sensor=false&libraries=geometry,places"></script>
      <%= javascript_include_tag 'application' %>
      <%= csrf_meta_tags %>
   </head>
   <body>
       <div id="map_canvas">
         <div id="info_panel">
            <div class="no_border">
               <div id="info_panel_upper">
                  <div id="player_name"><%= @user.name %></div>
                  <div id="player_lv">Lv0</div>
               </div>
               <div id="info_panel_lower">
                  <%= image_tag "http://graph.facebook.com/#{@user.fid}/picture", :id => "player_image", :size => "50x50" %>
                  <div id="bar_group">
                     <div class="info_bar">
                        <div id="hp_max" class="hpmp_bar hp_max"></div>
                        <div id="hp_now" class="hpmp_bar hp_now"></div>
                        <span id="hp_text" class="hpmp_text">HP 0/0</span>
                     </div>
                     <div class="info_bar">
                        <div id="mp_max" class="hpmp_bar mp_max"></div>
                        <div id="mp_now" class="hpmp_bar mp_now"></div>
                        <span id="mp_text" class="hpmp_text">MP 0/0</span>
                     </div>
                     <div class="info_bar">
                        <div id="exp_max" class="hpmp_bar exp_max"></div>
                        <div id="exp_now" class="hpmp_bar exp_now"></div>
                        <span id="exp_text" class="hpmp_text">EXP 0/0</span>
                     </div>
                  </div>
               </div>
            </div>
         </div>
         <div id="chat_panel">
            <div id="chat_history">
            </div>
            <div id="chat_panel_lower">
               <div id="chat_expand">&#9650;</div>
               <input id="chat_input" type="text"/>
               <button id="chat_button">SEND</button>
            </div>
         </div>
         <div id="right_panel">
            <div id="right_panel_upper">
               <div id="right_expand">&#9660;</div>
               <div id="inventory" class="right_title"><span class="tab">Inventory</span></div>
               <div id="equipment" class="right_title hidden"><span class="tab">Equipment</span></div>
               <div id="money" class="money">$100</div>
            </div>
            <div id="right_panel_lower">
               <div id="inventory_panel" class="right_panel_lower"></div>
               <div id="equipment_panel" class="right_panel_lower"></div>
            </div>
         </div>
         <div id="rune_socket">
            <div id="open_skill_tree">&#8853;</div>
            <div id="rune_title">Runes</div>
            <div id="socket_row">
              <%= image_tag "socket.png", :id => "socket0", :size => "30x30" %><!--
              --><%= image_tag "socket.png", :id => "socket1", :size => "30x30" %><!--
              --><%= image_tag "socket.png", :id => "socket2", :size => "30x30" %><!--
              --><%= image_tag "socket.png", :id => "socket3", :size => "30x30" %><!--
              --><%= image_tag "socket.png", :id => "socket4", :size => "30x30" %><!--
              --><%= image_tag "socket.png", :id => "socket5", :size => "30x30" %><!--
              --><%= image_tag "socket.png", :id => "socket6", :size => "30x30" %><!--
              --><%= image_tag "socket.png", :id => "socket7", :size => "30x30" %><!--
              --><%= image_tag "socket.png", :id => "socket8", :size => "30x30" %>
            </div>
         </div>
         <canvas id="skill_tree_panel" width="800" height="600" style="display:none;"></canvas>
           <script type="text/javascript">
              // TODO draw text: handle later
              /*window.onload=function() {
                canvas = document.getElementById("skill_tree_panel");
                var context = canvas.getContext("2d");
                context.font = "25pt Calibri";
                context.fillStyle = "#ffffff"
                context.fillText("Skill Build", 50, 70);
                }*/
              var mouse_is_inside = true;
              $(document).ready(function() {
                $('#skill_tree_panel').hover(function(){
                  mouse_is_inside=true;
                }, function(){
                  mouse_is_inside=false;
                });
                $("body").mouseup(function(){
                  if(!mouse_is_inside) {
                    $('#open_skill_tree').trigger('click');
                    mouse_is_inside = true;
                  }
                  //$('#skill_tree_panel').hide();
                });
              });
            </script>

            <%= display(@user.skill_tree) %>
            <script type="text/javascript">
              CIR_GRAY = "333377";
              CIR_LIGHT = "AAAAFF";

              parentof = new Array();
              lstate = new Array();
              estate = new Array();
              runex = new Array();
              runey = new Array();
              runetype = new Array();
              runesid = new Array();
              equiprune = new Array(-1, -1, -1, -1, -1, -1, -1, -1, -1);
              idmap = {}
              function getStates() {
                for(var iid=1; iid<=15; iid++) {
                  var id = iid;
                  $.get("skill_tree/query/<%=@user.id%>/"+id, (function(id){
                  return function(data) {
                    var sid = data.id;
                    console.log(data);
                    if(data.ancestry != null) {
                      var arr = data.ancestry.split('/');
                      parentof[id] = parseInt(arr[arr.length-1]);
                    } else parentof[id] = -1;
                    lstate[id] = data.learnt;
                    estate[id] = data.equipped;
                    runex[id] = 400 + parseFloat(data.x);
                    runey[id] = 300 + parseFloat(data.y);
                    console.log(id.toString() + " " + runex[id].toString() + " " + runey[id].toString())
                    runetype[id] = data.name;
                    runesid[id] = sid;
                    idmap[sid] = id;
                    initView(id);
                    }
                    })(iid));
                }
                // TODO: should handle callback better here
                initLink();
              }
              function initView(i) {
                //console.log(i + " " + lstate[i] + " " + estate[i]);
                if(estate[i]) drawCircle(i, CIR_LIGHT);
                else if(lstate[i]) drawCircle(i, CIR_GRAY);
              }
              function initLink() {
                canvas = document.getElementById("skill_tree_panel");
                console.log(canvas);
                canvas.addEventListener("click", function(e) {
                  var x = e.pageX;
                  var y = e.pageY;
                  x -= canvas.offsetLeft;
                  y -= canvas.offsetTop;
                  
                  for(var i=1; i<=15; i++) {
                    var x1 = runex[i] - 35.0/2;
                    var x2 = runex[i] + 35.0/2;
                    var y1 = runey[i] - 35.0/2;
                    var y2 = runey[i] + 35.0/2;
                    if(x>=x1 && x<=x2 && y>=y1 && y<=y2) {
                    console.log(i.toString() + "!")
                      click(i);
                      return;
                    }
                  }
                }, false);
                for(var i=0;i<9;i++){
                    $('#socket'+i).click(function(e){
                        e.preventDefault();
                        for(var j=0;j<9;j++)$('#socket'+j).removeClass('rune_selected');
                        $(this).addClass('rune_selected');
                    })
                } 
              }

              function drawTheCircle(centerX, centerY, radius, color) {
                canvas = document.getElementById("skill_tree_panel");
                var context = canvas.getContext("2d");
                context.beginPath();
                context.arc(centerX, centerY, radius, 0, 2 * Math.PI, false);
                //if(color == CIR_LIGHT) context.lineWidth = 2;
                //else context.lineWidth = 1;
                context.lineWidth = 2;
                context.strokeStyle = color;
                context.stroke();
                //console.log(" "+centerX+" "+centerY+" "+radius);
              }
              function drawCircle(id, color) {
                drawTheCircle(runex[id], runey[id], 19, color);
              }

              function cmprune(ia, ib) {
                if(ia<0&&ib<0) return 0;
                if(ia<0) return ;
                if(ib<0) return -1;
                return runetype[ia].localeCompare(runetype[ib]);
              }
              function redrawSocket() {
                equiprune.sort(cmprune);
                for(var i=0; i<9; i++) {
                  console.log(equiprune[i]);
                  if(equiprune[i]>=0) {
                    console.log(runetype[equiprune[i]]);
                    console.log($('#socket'+i));
                  }
                  if(equiprune[i]<0) $('#socket'+i).attr("src", "assets/socket.png");
                  else $('#socket'+i).attr("src", "assets/"+runetype[equiprune[i]]+"_equipped.png");
                }
              }
              function vacateSocket(id) {
                for(var i=0; i<9; i++) {
                  if(equiprune[i]==id) {
                    equiprune[i] = -1;
                    redrawSocket();
                    return;
                  }
                }
              }
              function populateSocket(id) {
                //alert("!");
                for(var i=0; i<9; i++) {
                  if(equiprune[i]==-1) {
                    console.log("equip "+id);
                    equiprune[i] = id;
                    redrawSocket();
                    return;
                  }
                }
                // full
                unequip(equiprune[Math.floor(Math.random()*9)]);
                populateSocket(id);
              }
              function learn(id) {
                if(lstate[id]) return; // already learnt
                lstate[id] = true;
                // learn TODO invoke controller learn
                drawCircle(id, CIR_GRAY);
              }
              function equip(id) {
                estate[id] = true;
                // equip TODO invoke controller equip
                drawCircle(id, CIR_LIGHT);
                populateSocket(id);
              }
              function unequip(id) {
                estate[id] = false;
                // unequip TODO invoke controller unequip
                drawCircle(id, CIR_GRAY);
                vacateSocket(id);
              }
              function click(id) {
              if(parentof[id]!=-1 && lstate[idmap[parentof[id]]]==false) return;
                if(lstate[id]) {
                  if(estate[id]) unequip(id);
                  else equip(id);
                } else {
                  learn(id);
                }
              }
            </script>
            <!--<h1 class="skill_tree_title">Skill Build</h1>-->
            <!--</canvas>-->
      </div>
      <div id="modal">
          <div id="store" class="modal_window">
          </div>
          <div id="dialog" class="modal_window">
              <div class="modal_head">
                 <div class="modal_title">Do you want to eat banana?</div>
                 <div class="modal_close">&#215;</div>
              </div>
              <div class="modal_body">
                 Eating bananas is good for your health!
              </div>
              <div class="modal_bar">
                 <div id="modal_ok" class="modal_button">OK</div>
                 <div id="modal_cancel" class="modal_button">Cancel</div>
              </div>
          </div>
          <div id="modal_mask">&nbsp;</div>
      </div>
   </body>
</html>